### ISSUE TITLE
Section 1

### ISSUE THREAD

**Issue by DevelopmentByDavid** [CS-UCR/better-banner#5]

**Comment by msalloum** [comment]
Just wondering what the sections numbers refer to?

**Comment by DevelopmentByDavid** [comment]
They are the sections corresponding to the [design document template](https://docs.google.com/document/d/14np37Bxmp2jl6LDdaOGFVxfkNXmHUVc3EkuMcnwQRY8/edit).  We talked about them all during lab and divvied up the work for the actual writing based on what people wanted to do.
